iPlug2: IVectorBase Class Reference
IVectorBase Class Reference
IGraphics::IControls::BaseControls
A base interface to be combined with IControl for vectorial controls "IVControls", in order for them to share a common style If you need more flexibility, you're on your own!
#include <IControl.h>
Public Member Functions
IVectorBase (const IColor *pBGColor=&DEFAULT_BGCOLOR, const IColor *pFGColor=&DEFAULT_FGCOLOR, const IColor *pPRColor=&DEFAULT_PRCOLOR, const IColor *pFRColor=&DEFAULT_FRCOLOR, const IColor *pHLColor=&DEFAULT_HLCOLOR, const IColor *pSHColor=&DEFAULT_SHCOLOR, const IColor *pX1Color=&DEFAULT_X1COLOR, const IColor *pX2Color=&DEFAULT_X2COLOR, const IColor *pX3Color=&DEFAULT_X3COLOR)
IVectorBase (const IVStyle &style, bool labelInWidget=false, bool valueInWidget=false)
void AttachIControl (IControl *pControl, const char *label)
void AddColor (const IColor &color)
void AddColors (const IColor *pBGColor=0, const IColor *pFGColor=0, const IColor *pPRColor=0, const IColor *pFRColor=0, const IColor *pHLColor=0, const IColor *pSHColor=0, const IColor *pX1Color=0, const IColor *pX2Color=0, const IColor *pX3Color=0)
void SetColor (int colorIdx, const IColor &color)
void SetColors (const IColor &BGColor, const IColor &FGColor, const IColor &PRColor, const IColor &FRColor, const IColor &HLColor, const IColor &SHColor, const IColor &X1Color, const IColor &X2Color, const IColor &X3Color)
void SetColors (const IVColorSpec &spec)
const IColor & GetColor (int colorIdx) const
void SetLabelStr (const char *label)
void SetValueStr (const char *value)
void SetWidgetFrac (float frac)
void SetAngle (float angle)
void SetShowLabel (bool show)
void SetShowValue (bool show)
void SetRoundness (float roundness)
void SetDrawFrame (bool draw)
void SetDrawShadows (bool draw)
void SetShadowOffset (float offset)
void SetFrameThickness (float thickness)
void SetSplashRadius (float radius)
void SetSplashPoint (float x, float y)
void SetStyle (const IVStyle &style)
IRECT GetAdjustedHandleBounds (IRECT handleBounds) const
float GetRoundedCornerRadius (const IRECT &bounds) const
void DrawSplash (IGraphics &g)
virtual void DrawBackGround (IGraphics &g, const IRECT &rect)
virtual void DrawWidget (IGraphics &g)
virtual void DrawLabel (IGraphics &g)
virtual void DrawValue (IGraphics &g, bool mouseOver)
void DrawHandle (IGraphics &g, EVShape shape, const IRECT &bounds, bool pressed, bool mouseOver)
void DrawPressableCircle (IGraphics &g, const IRECT &bounds, float radius, bool pressed, bool mouseOver)
void DrawPressableEllipse (IGraphics &g, const IRECT &bounds, bool pressed, bool mouseOver)
IRECT DrawPressableRectangle (IGraphics &g, const IRECT &bounds, bool pressed, bool mouseOver, bool roundTopLeft=true, bool roundTopRight=true, bool roundBottomLeft=true, bool roundBottomRight=true)
/todo
IRECT DrawPressableTriangle (IGraphics &g, const IRECT &bounds, bool pressed, bool mouseOver, float angle)
Draw a triangle-shaped vector button.
IRECT MakeRects (const IRECT &parent, bool hasHandle=false)
Protected Attributes
IControl * mControl = nullptr
WDL_TypedBuf< IColor > mColors
IVStyle mStyle
bool mLabelInWidget = false
bool mValueInWidget = false
float mSplashRadius = 0.f
float mSplashX = 0.f
float mSplashY = 0.f
float mMaxSplashRadius = 50.f
IRECT mWidgetBounds
IRECT mLabelBounds
IRECT mValueBounds
WDL_String mLabelStr
WDL_String mValueStr
Detailed Description
A base interface to be combined with IControl for vectorial controls "IVControls", in order for them to share a common style If you need more flexibility, you're on your own!
Definition at line 588 of file IControl.h.
Member Function Documentation
IRECT IVectorBase::DrawPressableRectangle (IGraphics & g, const IRECT & bounds, bool pressed, bool mouseOver, bool roundTopLeft = true, bool roundTopRight = true, bool roundBottomLeft = true, bool roundBottomRight = true) inline
/todo
Parameters
IGraphics&g /todo
bounds /todo
pressed /todo
mouseOver /todo
Returns
/todo
Definition at line 828 of file IControl.h.
References IGraphics::DrawRoundRect(), IGraphics::FillRoundRect(), and IRECT::GetTranslated().
Referenced by IVSwitchControl::Draw(), IVTabSwitchControl::Draw(), and IVSwitchControl::OnInit().
IRECT IVectorBase::DrawPressableTriangle (IGraphics & g, const IRECT & bounds, bool pressed, bool mouseOver, float angle) inline
Draw a triangle-shaped vector button.
Parameters
g The IGraphics context used for drawing
bounds Where to draw the button
pressed Whether to draw the button pressed or unpressed
mouseOver Whether mouse is currently hovering on control
Definition at line 867 of file IControl.h.
References IGraphics::DrawTriangle(), IGraphics::FillTriangle(), IRECT::GetFromBottom(), IRECT::GetFromTop(), IRECT::GetMidVPadded(), IRECT::GetReducedFromBottom(), IRECT::GetReducedFromTop(), IRECT::GetScaledAboutCentre(), IRECT::GetTranslated(), IRECT::H(), IRECT::MW(), and IRECT::W().
Referenced by IVRangeSliderControl::Draw().
The documentation for this class was generated from the following file:
IControl.h